backend:
  name: github
  repo: seandelaney/decap-example
  branch: main

media_folder: "content/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    create: true
    files:
    - label: "Home"
      name: "home"
      file: "content/pages/index.md"
      slug: "{{slug}}"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Slug", name: "slug", widget: "string", required: true }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown", editor_components: [] }
        - label: "Navigation"
          name: "eleventyNavigation"
          widget: "object"
          fields:
            - { label: "Key", name: "key", widget: "string" }
            - { label: "Order", name: "order", widget: "number" }
    - label: "About"
      name: "about"
      file: "content/pages/about.md"
      slug: "{{slug}}"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Slug", name: "slug", widget: "string", pattern: ["^[a-z0-9-]+$", "Lowercase letters, numbers, and hyphens only"], required: true }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown", editor_components: [] }
        - label: "Navigation"
          name: "eleventyNavigation"
          widget: "object"
          fields:
            - { label: "Key", name: "key", widget: "string" }
            - { label: "Order", name: "order", widget: "number" }
    - label: "Blog"
      name: "blog"
      file: "content/pages/blog.md"
      slug: "{{slug}}"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Slug", name: "slug", widget: "string", pattern: ["^[a-z0-9-]+$", "Lowercase letters, numbers, and hyphens only"], required: true }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown", editor_components: [] }
        - label: "Navigation"
          name: "eleventyNavigation"
          widget: "object"
          fields:
            - { label: "Key", name: "key", widget: "string" }
            - { label: "Order", name: "order", widget: "number" }
  - name: "blogPosts"
    label: "Blog Posts"
    folder: "content/blog"
    #filter:
    #  field: language
    #  value: en
    #  fields:
    #    - { label: "Language", name: "language" }
    create: true
    slug: "{{slug}}"
    summary: "{{title}} {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", pattern: ["^[a-z0-9-]+$", "Lowercase letters, numbers, and hyphens only"], required: true }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", editor_components: [] }
      - { label: "Publish Date", name: "date", widget: "datetime" }

